function f = F(in1,z3)
%F
%    F = F(IN1,Z3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    11-Apr-2022 01:47:55

x = in1(1,:);
z1 = in1(2,:);
z2 = in1(3,:);
t2 = x.*z1;
f = [-z1+x.^2;z2+tanh(x)+t2.*z1;t2+z3.*(sin(x)+2.0)+z1.*z2];
