function out1 = Y1(in1,alpha,in3)
%Y1
%    OUT1 = Y1(IN1,ALPHA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    27-Mar-2022 06:03:42

qd1 = in3(1,:);
qd2 = in3(2,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = -x2;
t3 = qd2+t2;
t4 = cos(t3);
t5 = sin(t3);
out1 = reshape([alpha.*x1,0.0,alpha.*x2,alpha.*(x1+x2),-t5.*x4.^2+alpha.*t4.*x1.*2.0+alpha.*t4.*x2,t5.*x3.^2+alpha.*t4.*x1,-x3,0.0,0.0,-x4,-tanh(x3),0.0,0.0,-tanh(x4),qd1-x1,0.0,0.0,t3],[2,9]);
