function out1 = Y2(in1,alpha,in3)
%Y2
%    OUT1 = Y2(IN1,ALPHA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    27-Mar-2022 06:03:43

qd2 = in3(2,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = alpha.*x1;
t3 = -x2;
t4 = t2+x3;
t5 = qd2+t3;
t6 = cos(t5);
t7 = sin(t5);
out1 = reshape([(alpha.*x3)./2.0,0.0,(alpha.*x4)./2.0,(alpha.*(x3+x4))./2.0,x4.*((alpha.*t6)./2.0+t4.*t7+(t7.*(x4+alpha.*x2))./2.0)+alpha.*t6.*x3,(alpha.*t6.*x3)./2.0+(t4.*t7.*x4)./2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,9]);
