function out1 = Y(in1,alpha,in3)
%Y
%    OUT1 = Y(IN1,ALPHA,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    30-Apr-2022 17:27:38

ddqd1 = in3(5,:);
ddqd2 = in3(6,:);
dqd1 = in3(3,:);
dqd2 = in3(4,:);
qd1 = in3(1,:);
qd2 = in3(2,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = alpha.*x1;
t3 = alpha.*x3;
t4 = alpha.*x4;
t5 = -x2;
t6 = dqd1+t2;
t7 = qd2+t5;
t8 = cos(t7);
t9 = sin(t7);
out1 = reshape([ddqd1+t3,0.0,ddqd2+t4,ddqd1+ddqd2+t3+t4,ddqd1.*t8.*2.0+ddqd2.*t8+t3.*t8.*2.0+t4.*t8+t9.*(x3+x4).*(dqd2+alpha.*x2)-t6.*t9.*x4,ddqd1.*t8+t3.*t8-t6.*t9.*x3,dqd1-x3,0.0,0.0,dqd2-x4,-tanh(x3),0.0,0.0,-tanh(x4),qd1-x1,0.0,0.0,t7],[2,9]);
